# Generated by Django 4.1.1 on 2022-09-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="item",
            table="items",
        ),
    ]
