name: Rishat Task
on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
        - name: Install dependencies
          run: |
            python -m pip install -U pip
            pip install -r requirements.dev.txt
        - name: Lint
          run: |
            ./scripts/lint.sh
        - name: Test with pytest
          run: |
            pytest
        - name: Heroku deploy
          run:
            heroku container:login
            heroku container:push -a rishat-task web
            heroku container:release -a rishat-task web

